### ISSUE TITLE
Install and configure everything for M269

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/virtual-env#4]
To ease things for users, we need a script that takes as argument the M269 folder, e.g. `~/OU/m269-23j` or `/mnt/c/Users/me/OU/m269-23j`, and does the following:

- creates the M269 folder if it doesn't exist
- creates environment `venv` in the M269 folder with the software in `m269-requirements.txt`
  - if there's a message about missing Python 3.10, user has to install it and restart script
- creates alias  `m269-23j` that `cd <M269 folder>; source venv/bin/activate`
- creates alias `nb` to start Jupyter notebooks
- puts `allowed.py` and `m269.json` in the M269 folder 
- creates `~/.jupyter/custom/` if it doesn't exist and puts `custom.css` there

**Comment by densnow** [comment]
I might as well mention this here as it is kind of related, but not worth raising an issue over. Do we want to add `pytype` to `m269-requirements.txt`. Since we are requiring the user to have Python 3.10 and adding `allowed` to the folder, I think it makes sense.

**Comment by mwermelinger** [comment]
Issue handled by new [repo](https://github.com/dsa-ou/m269-installer).
